"""Reject any multi-team marker, not only TOT, in the core identity tables.

Supersedes the four `*_not_tot` check constraints created in
`0002_core_team_player_season`. Those accepted `5TM` — a value that exists in
the cached archive — as an ordinary team code.

The conditions below were generated by
`nba_data.domain.team_codes.reject_synthetic_team_code_sql`, then **frozen into
this file**. A revision is a historical record of one schema change: if it read
the module at run time, re-running it after a rule change would produce a
different schema than it produced the first time, and two databases at the same
revision could disagree. `db/models/core.py` still calls the generator, so the
mapped metadata tracks the current rule; `tests/unit/test_migration_snapshots.py`
asserts this frozen text still matches it, and fails when the rule moves on
without a follow-up revision.

Revision ID: 0006_synthetic_team_codes
Revises: 0005_postseason_stats_tables
Create Date: 2026-08-16 00:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0006_synthetic_team_codes"
down_revision: str | None = "0005_postseason_stats_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TEAMS_BREF_ID_NOT_SYNTHETIC = """
    basketball_reference_team_id IS NULL OR NOT (upper(trim(basketball_reference_team_id)) =
    'TOT' OR (upper(trim(basketball_reference_team_id)) LIKE '%TM' AND replace( replace(
    replace( replace( replace( replace( replace( replace( replace( replace(
    upper(trim(basketball_reference_team_id)), '0', ''), '1', ''), '2', ''), '3', ''), '4',
    ''), '5', ''), '6', ''), '7', ''), '8', ''), '9', '') = 'TM' AND
    ((length(upper(trim(basketball_reference_team_id))) = 3 AND
    substr(upper(trim(basketball_reference_team_id)), 1, 1) IN ('2', '3', '4', '5', '6', '7',
    '8', '9')) OR (length(upper(trim(basketball_reference_team_id))) > 3 AND
    substr(upper(trim(basketball_reference_team_id)), 1, 1) IN ('1', '2', '3', '4', '5', '6',
    '7', '8', '9')))))
"""

TEAMS_CURRENT_ABBREVIATION_NOT_SYNTHETIC = """
    current_abbreviation IS NULL OR NOT (upper(trim(current_abbreviation)) = 'TOT' OR
    (upper(trim(current_abbreviation)) LIKE '%TM' AND replace( replace( replace( replace(
    replace( replace( replace( replace( replace( replace( upper(trim(current_abbreviation)),
    '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''), '6', ''), '7', ''), '8', ''),
    '9', '') = 'TM' AND ((length(upper(trim(current_abbreviation))) = 3 AND
    substr(upper(trim(current_abbreviation)), 1, 1) IN ('2', '3', '4', '5', '6', '7', '8',
    '9')) OR (length(upper(trim(current_abbreviation))) > 3 AND
    substr(upper(trim(current_abbreviation)), 1, 1) IN ('1', '2', '3', '4', '5', '6', '7',
    '8', '9')))))
"""

TEAM_ALIASES_ABBREVIATION_NOT_SYNTHETIC = """
    NOT (upper(trim(abbreviation)) = 'TOT' OR (upper(trim(abbreviation)) LIKE '%TM' AND
    replace( replace( replace( replace( replace( replace( replace( replace( replace( replace(
    upper(trim(abbreviation)), '0', ''), '1', ''), '2', ''), '3', ''), '4', ''), '5', ''),
    '6', ''), '7', ''), '8', ''), '9', '') = 'TM' AND ((length(upper(trim(abbreviation))) = 3
    AND substr(upper(trim(abbreviation)), 1, 1) IN ('2', '3', '4', '5', '6', '7', '8', '9'))
    OR (length(upper(trim(abbreviation))) > 3 AND substr(upper(trim(abbreviation)), 1, 1) IN
    ('1', '2', '3', '4', '5', '6', '7', '8', '9')))))
"""

TEAM_SEASONS_ABBREV_NOT_SYNTHETIC = """
    NOT (upper(trim(team_abbreviation)) = 'TOT' OR (upper(trim(team_abbreviation)) LIKE '%TM'
    AND replace( replace( replace( replace( replace( replace( replace( replace( replace(
    replace( upper(trim(team_abbreviation)), '0', ''), '1', ''), '2', ''), '3', ''), '4', ''),
    '5', ''), '6', ''), '7', ''), '8', ''), '9', '') = 'TM' AND
    ((length(upper(trim(team_abbreviation))) = 3 AND substr(upper(trim(team_abbreviation)), 1,
    1) IN ('2', '3', '4', '5', '6', '7', '8', '9')) OR (length(upper(trim(team_abbreviation)))
    > 3 AND substr(upper(trim(team_abbreviation)), 1, 1) IN ('1', '2', '3', '4', '5', '6',
    '7', '8', '9')))))
"""


# (table, old constraint name, new constraint name, frozen condition, column,
#  whether the column is nullable — the last two only rebuild the `<> 'TOT'`
#  form that `downgrade` restores.)
CONSTRAINTS = (
    (
        "teams",
        "ck_core_teams_bref_id_not_tot",
        "ck_core_teams_bref_id_not_synthetic",
        TEAMS_BREF_ID_NOT_SYNTHETIC,
        "basketball_reference_team_id",
        True,
    ),
    (
        "teams",
        "ck_core_teams_current_abbreviation_not_tot",
        "ck_core_teams_current_abbreviation_not_synthetic",
        TEAMS_CURRENT_ABBREVIATION_NOT_SYNTHETIC,
        "current_abbreviation",
        True,
    ),
    (
        "team_aliases",
        "ck_core_team_aliases_abbreviation_not_tot",
        "ck_core_team_aliases_abbreviation_not_synthetic",
        TEAM_ALIASES_ABBREVIATION_NOT_SYNTHETIC,
        "abbreviation",
        False,
    ),
    (
        "team_seasons",
        "ck_core_team_seasons_abbrev_not_tot",
        "ck_core_team_seasons_abbrev_not_synthetic",
        TEAM_SEASONS_ABBREV_NOT_SYNTHETIC,
        "team_abbreviation",
        False,
    ),
)


def upgrade() -> None:
    for table, old_name, new_name, condition, _column, _nullable in CONSTRAINTS:
        op.drop_constraint(old_name, table, schema="core", type_="check")
        op.create_check_constraint(new_name, table, _one_line(condition), schema="core")


def downgrade() -> None:
    for table, old_name, new_name, _condition, column, nullable in reversed(CONSTRAINTS):
        op.drop_constraint(new_name, table, schema="core", type_="check")
        op.create_check_constraint(
            old_name,
            table,
            _reject_tot(column, nullable=nullable),
            schema="core",
        )


def _one_line(condition: str) -> str:
    """Undo the wrapping the snapshots carry for readability.

    The conditions are wrapped to fit the line limit, and `replace(` is followed
    by a space for the same reason. No string literal in them contains
    whitespace, so collapsing runs of it restores the generated text exactly.
    """

    return " ".join(condition.split()).replace("replace( ", "replace(")


def _reject_tot(column: str, *, nullable: bool) -> str:
    condition = f"{column} <> 'TOT'"
    return f"{column} IS NULL OR {condition}" if nullable else condition
