team_abbrev = {
    'Atlanta Hawks': 'ATL',
    'Boston Celtics': 'BOS',
    'Brooklyn Nets': 'BRK',
    'Charlotte Hornets': 'CHO',
    'Chicago Bulls': 'CHI',
    'Cleveland Cavaliers': 'CLE',
    'Dallas Mavericks': 'DAL',
    'Denver Nuggets': 'DEN',
    'Detroit Pistons': 'DET',
    'Golden State Warriors': 'GSW',
    'Houston Rockets': 'HOU',
    'Indiana Pacers': 'IND',
    'Los Angeles Clippers': 'LAC',
    'Los Angeles Lakers': 'LAL',
    'Memphis Grizzlies': 'MEM',
    'Miami Heat': 'MIA',
    'Milwaukee Bucks': 'MIL',
    'Minnesota Timberwolves': 'MIN',
    'New Orleans Pelicans': 'NOP',
    'New York Knicks': 'NYK',
    'Oklahoma City Thunder': 'OKC',
    'Orlando Magic': 'ORL',
    'Philadelphia 76ers': 'PHI',
    'Phoenix Suns': 'PHO',
    'Portland Trail Blazers': 'POR',
    'Sacramento Kings': 'SAC',
    'San Antonio Spurs': 'SAS',
    'Toronto Raptors': 'TOR',
    'Utah Jazz': 'UTA',
    'Washington Wizards': 'WAS',
    'Vancouver Grizzlies': 'VAN',
    'Seattle SuperSonics': 'SEA',
    'New Jersey Nets': 'NJN',
    'New Orleans Hornets': 'NOH',
    'Charlotte Bobcats': 'CHA',
    'Charlote Hornets Old': 'CHH',
    'New Orleans/Oklahoma City Hornets': 'NOK'
}

team_abbrev_old = {
    'Vancouver Grizzlies': 'VAN',
    'Seattle SuperSonics': 'SEA',
    'New Jersey Nets': 'NJN',
    'New Orleans Hornets': 'NOH',
    'Charlotte Bobcats': 'CHA',
    'Charlote Hornets Old': 'CHH',
    'New Orleans/Oklahoma City Hornets': 'NOK'
}
